### ISSUE TITLE
Standard user attributes are tracked as custom attributes.

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-segment-android#10]
In [identify()](https://github.com/Appboy/appboy-segment-android/blob/master/src/main/java/com/segment/analytics/android/integrations/appboy/AppboyIntegration.java#L103), birthday, email, firstName, lastName, gender, phone, and address are set to the standard user attributes. After that, it loops traits object and sets all traits as a custom attributes without filtering the standard trait keys. As a result, I can see these standard attributes are tracked as custom attributes too.

<img width="1080" alt="braze_custom_attributes" src="https://user-images.githubusercontent.com/13875691/58675338-bae41e80-8308-11e9-9a46-ea92c765738d.png">

For iOS integration, standard attributes are filtered out when setting the custom attributes as you can see (https://github.com/Appboy/appboy-segment-ios/blob/master/Pod/Classes/SEGAppboyIntegration.m#L139). So, android integration should be fixed.

**Comment by Bucimis** [comment]
@jamesyoon11 thanks for raising! we've fixed this in 2.4.1.
