### ISSUE TITLE
session start is not tracked

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-segment-android#12]
openSession() is called in the “onActivityStarted” method but “onActivityStarted” is never called when the app is opened after being closed. Therefore, session start is never tracked for the user launches the app if the user has force-quit it

https://github.com/Appboy/appboy-segment-android/blob/master/src/main/java/com/segment/analytics/android/integrations/appboy/AppboyIntegration.java#L261

Can it be fixed by calling openSession() right after Appboy instance is created?

https://github.com/Appboy/appboy-segment-android/blob/master/src/main/java/com/segment/analytics/android/integrations/appboy/AppboyIntegration.java#L71

**Comment by radixdev** [comment]
Only calling `openSession()` after instance creation would lead to incorrect session handling (imagine you start the app, background, then re-foreground, you'd not have a second session.)

Can you provide a small, reproducible sample app that demonstrates `onActivityStarted` and `openSession()` not getting called after a force-close? According to https://i.stack.imgur.com/Jk8de.png , that shouldn't be happening.

**Comment by jamesyoon11** [comment]
Yeah, it seems to be a race condition issue due to our cordova app. We cannot initialize Segment in pluginInitialize() for some reason so Appboy instance is created after onActivityStarted. FYI, I attached the sample app (Segment/Braze integration happens in Device.java:84)

[android.zip](https://github.com/Appboy/appboy-segment-android/files/3308105/android.zip)

**Comment by radixdev** [comment]
You could try initializing Segment in an Android Application class instead of the Cordova Device#execute block. Something like [this](https://stackoverflow.com/a/36107247/3745724) might work. Lastly, you can just call openSession yourself after setting up Segment since `openSession` calls are idempotent if you're in the same Activity still.

_I'd also recommend asking Segment for guidance on a Segment-Cordova-Braze integration._

**Comment by jamesyoon11** [comment]
I wish I could modify application class but our build platform is not that flexible. It has to be able to build it in Jenkins and there is no chance to update the android project after the build process is done. Anyway, thank you very much for looking into this. I am closing this since it is due to our cordova app limitation. I am going to find some workaround way.
