### ISSUE TITLE
unable to disable automatic_in_app_message_registration_enabled

### ISSUE THREAD

**Issue by ouchadam** [Appboy/appboy-segment-android#13]
Apologies if this is a segment issue

When the `Enable Automatic In-App Message Registration` is disabled in the segment dashboard, the value is omitted from the `ValueMap settings` which results in the default value of `true` being used.

![Screenshot 2019-08-27 at 14 09 03](https://user-images.githubusercontent.com/1848238/63774009-43586800-c8d4-11e9-8247-a33f1a78453f.png)

This ultimately means it's impossible to disable the in app message registration (without manually copying the integration).

Is this a known issue, or perhaps there's some misconfiguration on my side? 

Thanks!

**Comment by nelljohan** [comment]
+1

Same here, just tried this new mechanism to replace the custom integration I wrote for https://github.com/Appboy/appboy-segment-android/issues/7

Can confirm that the value is just missing from the settings map and then the `AppboyIntegration` defaults to `true`.

**Comment by chshapiro** [comment]
Hey @ouchadam and @nelljohan,

We've reached out to Segment asking them to fix this and will keep you updated on this thread. 

Thanks!

**Comment by slesinskik** [comment]
@chshapiro has this been fixed?

**Comment by ragdroid** [comment]
Any updates on this please?

**Comment by davidbielik** [comment]
Hi @ragdroid We've asked the Segment team to fix this. It would help if you can please raise a bug report with the Segment team as well so their dashboard configuration properly sends down `false` instead of omitting the value.

**Comment by ragdroid** [comment]
I see this is coming back now in Segment settings already
