### ISSUE TITLE
Double properties not tracked

### ISSUE THREAD

**Issue by badoualy** [Appboy/appboy-segment-android#15]
Per https://github.com/Appboy/appboy-segment-android/blob/master/src/main/java/com/segment/analytics/android/integrations/appboy/AppboyIntegration.java#L189

double properties seems to be ignored, however, when adding a number to the `ValueMap`, the backing map seems to use Double as default type.

**Comment by Bucimis** [comment]
@badoualy thanks for flagging! this will be in our next release

**Comment by Bucimis** [comment]
Hi @badoualy, support for double types traits values is now released - thanks again for reporting
