### ISSUE TITLE
How to set up User Subscriptions

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-segment-android#18]
Hi,

I am trying to send user subscriptions data. 

https://www.braze.com/docs/developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes/#setting-up-user-subscriptions

However, I am not able to find a documentation about how to do it. Can you please provide me some instruction?

**Comment by Bucimis** [comment]
Hi @jamesyoon11 

Subscription type must be set using our native Braze Android SDK's methods directly. The methods are available in the `AppboyUser` class, e.g. for push: https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/AppboyUser.html#setPushNotificationSubscriptionType-com.appboy.enums.NotificationSubscriptionType-

Sample usage: https://github.com/Appboy/appboy-android-sdk/blob/2af88009a097a4f447da303e525e24f0963ffea2/droidboy/src/main/java/com/appboy/sample/subscriptions/PushSubscriptionStateDialog.java#L32

**Comment by jamesyoon11** [comment]
Thank you for the prompt response @Bucimis 

Yeah, I know that the Braze SDK has the API. However, we are using the Segment/Braze integration and it is supposed to support all Braze tracks (user attributes and custom events) via Segment API calls. If we have to call the Braze SDK directly for certain user attributes, there is no point to use the Segment/Braze integration.

**Comment by Bucimis** [comment]
@jamesyoon11 you can gate the direct calls to the Braze API based on whether the Segment+Braze integration is active. Active or not, the Braze SDK will be compiled into the app so it shouldn't cause issues to reference it. 

I'll also leave feedback with our product team and see if its feasible to introduce a Segment wrapper API for subscription
