### ISSUE TITLE
Braze 6.0.0 is still present in the version 5.0.0

### ISSUE THREAD

**Issue by phuocth** [Appboy/appboy-segment-android#21]
Hi, accordingly to the change logs [https://github.com/Appboy/appboy-segment-android/blob/master/CHANGELOG.md#breaking], we should have the Braze SDK 8.1.0 to be included but I still find it is still the version 6. Is there any provision on this integration ? Thanks.

**Comment by chshapiro** [comment]
Hey @phuocth,

Thanks for raising! We're going to be releasing a new version in the next day or two that will import the newest Braze SDK version.

**Comment by chshapiro** [comment]
Hey @phuocth,

We just released 6.0.0 which uses version 9.0.0 of the Braze Android SDK. Feel free to reopen this issue if you have any further questions.
