### ISSUE TITLE
Update Braze sdk to 10.0.0

### ISSUE THREAD

**Issue by sergiandreplace** [Appboy/appboy-segment-android#22]
Latest Braze sdk is 10.0.0, but this project is still using sdk 9.0.0.

When could we expect this library to be updated?

Thanks in advance

**Comment by Bucimis** [comment]
@sergiandreplace Thanks for filling! We're looking to do this in the next 1-2 weeks. Out of curiosity, do you have a particular use case for using 10.0?

**Comment by sergiandreplace** [comment]
Thanks!

We do not have a specific use case, is just that some of our apps and components are really behind and we wanted to update them all and get as far as possible, and it will be a pity to not catch version 10 because this component.

**Comment by Bucimis** [comment]
Thanks for the context, we're aiming to update over the next ~2 weeks

**Comment by badoualy** [comment]
Dropping jetifier is a nice use case for 10.0.0 :)

**Comment by sergiandreplace** [comment]
Silly idea, maybe is worth to align the major version of this library with the major version of the sdk to make things easier

**Comment by Bucimis** [comment]
@sergiandreplace this is definitely a fun idea, but it would likely add too much of a coordination cost across our numerous SDKs and teams to get done in the near-term.

**Comment by sergiandreplace** [comment]
🤷 Sure, it was just an idea, you know better its feasibility better than me :)

**Comment by sergiandreplace** [comment]
Any news or ETA? 
Thanks

**Comment by Bucimis** [comment]
@sergiandreplace sorry for the slow update, we're in the QA process currently and aiming to release ~EOW

**Comment by sergiandreplace** [comment]
Great! Thanks for the update

**Comment by Bucimis** [comment]
@sergiandreplace released :)

**Comment by sergiandreplace** [comment]
![tenor-74243795](https://user-images.githubusercontent.com/541020/97035027-0898a100-1566-11eb-8eb0-c2e39729fe7e.gif)
