### ISSUE TITLE
Please update to use the latest base SDK

### ISSUE THREAD

**Issue by RyanNewsom** [Appboy/appboy-segment-android#24]
Currently you are using 10.0.0 of the base sdk, 12.0.0 is the latest
https://github.com/Appboy/appboy-android-sdk/tags
https://github.com/Appboy/appboy-android-sdk/compare/v10.0.0...v12.0.0

**Comment by chshapiro** [comment]
Hey @RyanNewsom,

This will be updated in the coming weeks.

**Comment by chshapiro** [comment]
Hey @RyanNewsom,

Our newest release 8.0.2 uses version 13.1.2 of the Android SDK.
