### ISSUE TITLE
Version v8.0.0 is missing in Maven?

### ISSUE THREAD

**Issue by phuocth** [Appboy/appboy-segment-android#27]
Hello. Could you please check if we have upload the latest version v8.0.0 to Maven? I think it is still with v7.0.0. 
Thanks.
![2EBE9564-AC0C-4E76-95F1-9A268CD9DC20](https://user-images.githubusercontent.com/7509592/113133100-81a0d080-9249-11eb-9b13-d3f59aa88160.jpeg)

**Comment by phuocth** [comment]
Hi Jared @Bucimis ,
Followed it. 
<img width="631" alt="Screen Shot 2021-04-01 at 8 52 54 AM" src="https://user-images.githubusercontent.com/7509592/113232603-b0f62280-92c7-11eb-96ff-c3c7a5fdab7e.png">

However I still get the compile error:
`Could not find com.appboy:appboy-segment-integration:8.0.0.`

I tried the URL in browser and got a 404.
<img width="1281" alt="Screen Shot 2021-04-01 at 8 42 40 AM" src="https://user-images.githubusercontent.com/7509592/113232274-0a118680-92c7-11eb-9062-3c373e9d9b04.png">

**Comment by Bucimis** [comment]
@phuocth Hey Patrick, sorry about that. We just fixed an issue with our Maven repo. Can you try again?

**Comment by phuocth** [comment]
@Bucimis Thanks Jared. All good now.

**Comment by MarinaShaposhnikova** [comment]
Hello @phuocth may you please mention it on README?

**Comment by MarinaShaposhnikova** [comment]
Hello @Bucimis may you please mention it on README?

**Comment by Bucimis** [comment]
@MarinaShaposhnikova 8.0.0+ is hosted by github, you will need to follow https://github.com/Appboy/appboy-segment-android/blob/master/CHANGELOG.md#breaking-3 (see https://segment.com/docs/connections/destinations/catalog/braze/#android for the complete list of maven repos needed)

**Comment by MarinaShaposhnikova** [comment]
Hi @Bucimis the maven links are pointed to insecure protocol http.

We prefer to use only secure connections and Gradle 7+ asks to specify insecure protocols in the code.

```
Redirecting from secure protocol to insecure protocol, without explict opt-in, is unsupported. 'https://bright.github.io/maven-repo/' is redirecting to 'http://blog.brightinventions.pl/maven-repo/com/appboy/appboy-segment-integration/11.0.0/appboy-segment-integration-11.0.0.pom'. Switch Maven repository 'maven3(https://bright.github.io/maven-repo/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols
```

**Comment by radixdev** [comment]
Hi @MarinaShaposhnikova ,

You may safely change the protocol to `https` for the Braze maven repository as it is hosted on Github pages.
