### ISSUE TITLE
Upgrade Braze SDK to v13.1.2

### ISSUE THREAD

**Issue by phuocth** [Appboy/appboy-segment-android#28]
Hi @Bucimis Jared and team,
Any possibility we could upgrade the Braze SDK to v13.1.2 as per recommendation from Braze team (captured below) ? If yes, could you please let us know when we could get the updated SDK ? 
I understand that we have upgraded to v13.1.1 but the v13.1.2 has been released and recommended.
Thanks a lot.
<img width="594" alt="Screen Shot 2021-04-08 at 9 55 12 AM" src="https://user-images.githubusercontent.com/7509592/113961985-1b234000-9851-11eb-8ed3-c55cd6c4af56.png">

**Comment by chshapiro** [comment]
Hey @phuocth,

We just released version 8.0.2 which uses version 13.1.2 of the Android SDK.

Please let us know if you run into any further issues.

**Comment by phuocth** [comment]
Hi @chshapiro Chava,
We've been able to upgrade to v8.0.2 which uses Braze v13.1.2. Thank you.
