### ISSUE TITLE
`maven-metadata.xml` is missing version 8.0.2 and 9.0.0

### ISSUE THREAD

**Issue by abdullah-kasim** [Appboy/appboy-segment-android#30]
The xml located here, is missing version 8.0.2 and 9.0.0: http://appboy.github.io/appboy-segment-android/sdk/com/appboy/appboy-segment-integration/maven-metadata.xml . Is this intended?

~~I'm unable to update to 9.0.0 due to this.~~ For now, I force-updated using `implementation 'com.appboy:appboy-segment-integration:9.0.0@aar'`.

**Comment by chshapiro** [comment]
Hey @abdullah-kasim,

The file has been updated now. Please let us know if you continue to run into any issues.
