### ISSUE TITLE
Backwards compatibility with the latest version appboy-android-sdk

### ISSUE THREAD

**Issue by krasov** [Appboy/appboy-segment-android#31]
In the latest version of appboy-android-sdk(17.0.0) the StringUtils class was removed, which is used in this segment integration sdk.

**Comment by bryanlogan** [comment]
Sorry about that.  It should be "import com.braze.support.StringUtils;".   We'll get it fixed.

**Comment by chshapiro** [comment]
Hey @krasov,

Our latest version of the Appboy-Segment SDK supports version 15.0.0 of appboy-android-sdk. Our next release will support the latest version 17.0.0.

**Comment by jMavarez** [comment]
When should we be expecting the next release?
