### ISSUE TITLE
Version 23.0.1 available

### ISSUE THREAD

**Issue by k-farhan** [Appboy/appboy-segment-android#34]
Hi,

Thank you so much for the hard work.
We are using bundled SDK in our projects and were testing the Android13 related changes. Recently our QA team flagged one issue that we are not receiving the push notifications unless we relaunch the app.
We find out there there's new version available with the potential fix [here](https://github.com/Appboy/appboy-android-sdk/commit/67f2b8392c22aef2a96a0573a9809aac282e58f7#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR8)
We would request you to please update the library as soon as possible as its blocking our further test cases and might impact our release and timelines as well.

Hoping to receive the feedback early as possible :)

**Comment by chshapiro** [comment]
Hi @k-farhan ,
We will release with a version update this week.
Thanks for reporting!

**Comment by chshapiro** [comment]
hey @k-farhan ,

We just released version 14.0.0 which uses version 23.0.1 of our Android SDK.
