### ISSUE TITLE
Class not found error in latest version

### ISSUE THREAD

**Issue by etazhar** [Appboy/appboy-segment-android#37]
getting this error on runtime

    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appboy/enums/SdkFlavor;

**Comment by martynamaron** [comment]
Seeing the same in my app - any chance of fixing this? 👀

**Comment by etazhar** [comment]
Are you using segmentation SDK in your project?

**Comment by martynamaron** [comment]
Using the following dependencies:

```
...
        maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
        maven { url "https://appboy.github.io/appboy-segment-android/sdk" }
...
```

```
    segmentAnalytics = "com.segment.analytics.android:analytics:4.11.3"
    segmentBrazeIntegration = "com.appboy:appboy-segment-integration:14.0.1"
    braze = "com.appboy:android-sdk-ui:24.3.0"
```

**Comment by bryanlogan** [comment]
Overriding the android-sdk-ui is going to cause issues. Is there a particular reason you're going to that level?

**Comment by martynamaron** [comment]
I see - looks like it's only needed to have access to `BrazeInAppMessageManager`. I'm not sure it's still needed though, so I'll look at removing it. Do you think not implementing the `android-sdk-ui` will solve the issue?

**Comment by etazhar** [comment]
segment_version = '4.11.3'
    segment_appboy_version = '14.0.1'
     app_boy_version= "23.0.1"
     
   use these version if you're using segment sdk

**Comment by bryanlogan** [comment]
I'll get a new version out that uses the latest Braze and Segment SDK's. If you're ready to move to the newer Segment Kotlin SDK, we do have https://github.com/braze-inc/braze-segment-kotlin

**Comment by bryanlogan** [comment]
A new segment-android 15.0.0 has been released with the latest Android SDK and Segment SDK. This should resolve the issue. If you're referencing the enum directly, it's now found under `com.braze` instead of `com.appboy`

**Comment by egor-n** [comment]
Hi @bryanlogan, could you please push a git tag corresponding to the 15.0.0 release. Thank you!
