### ISSUE TITLE
Integration with Segment but is trying to catch the API from appboy.xml

### ISSUE THREAD

**Issue by xanexpt** [Appboy/appboy-segment-android#5]
Hello,

I'm using 
com.appboy:appboy-segment-integration:2.1.1
com.zendesk:support:2.0.0

In the last 2 days I had a few crashes in production in the Android OS 5.1.1, 6.0, 6.0.1 and 7.1.1 in the brands LGE, ZTE, Motorola, Alco and others.

Isn't the segment supposed to support braze with the needed information for the configuration?

Fatal Exception: java.lang.RuntimeException: Unable to read the Braze API key from the res/values/appboy.xml file. See log for more details.
       at com.appboy.configuration.AppboyConfigurationProvider.getAppboyApiKey(SourceFile:199)
       at com.appboy.Appboy.e(SourceFile:299)
       at com.appboy.Appboy.f(SourceFile:77)
       at com.appboy.Appboy$18.run(SourceFile:275)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Bucimis** [comment]
Hi @xanexpt,

Yes, the Braze API key is passed from the Segment wrapper to the Braze SDK so a local appboy.xml containing a Braze API key is not strictly required. This crash looks like a potential race condition between Segment passing the Braze API key down and Braze initializing. Do you make any other calls to Appboy API besides the ones you make through Segment? 

Separately, if you're willing, adding the Braze API key to a local appboy.xml in your build should stop these crashes altogether (except in ultra-rare cases where there's corruption and the app is unable to read its resources).

**Comment by xanexpt** [comment]
Hello,

The early calls I have with Appboy I have them protected with 
Analytics.with(context).onIntegrationReady(APPBOY_STRING...

I found one before, 
AppboyLogger.setLogLevel(AppboyLogger.SUPPRESS);
I'm going to protect it also with onIntegrationReady and check if this is the problem 

Do you think maybe this is the problem?

**Comment by Bucimis** [comment]
@xanexpt 

The `AppboyLogger` call is unlikely to be the cause since its a static method. We only read the API key in the context of a particular instance of Appboy. Are there any other calls to Appboy that aren't gated? The only other explanation i can think of is a possible race condition with `onIntegrationReady()`
