### ISSUE TITLE
Manual In-App Message Registration & Segment Integration

### ISSUE THREAD

**Issue by nelljohan** [Appboy/appboy-segment-android#7]
Hi,

I ran into an issue where we wanted to defer In-App messages to show up on specific Activities.
(Messages showed up behind our login dialog and would never be visible on first boot)

This is relatively easy when following the manual registration steps as defined here: https://www.braze.com/documentation/Android/#in-app-messaging, but when using this segment integration there is no way I could find to avoid these methods doing registration automatically:

```
public class AppboyIntegration extends Integration<Appboy> {
  ...
 public void onActivityResumed(Activity activity) {
        super.onActivityResumed(activity);
        AppboyInAppMessageManager.getInstance().registerInAppMessageManager(activity);
    }

    public void onActivityPaused(Activity activity) {
        super.onActivityPaused(activity);
        AppboyInAppMessageManager.getInstance().unregisterInAppMessageManager(activity);
    }
...
```

For now I just went ahead and wrote my own custom version of `AppboyIntegration` that doesn't override these methods and that is working perfectly, but it would be nice if there was an easier way to achieve this via configuration.

**Comment by Bucimis** [comment]
Hi @nelljohan thanks for filing and this is definitely a limitation we should get rid of. We should have a release fixing this in the coming few weeks

**Comment by Bucimis** [comment]
@nelljohan thanks again for contacting us. We've finished the work to specify adding manual IAM registration through a segment remote configuration field and will be releasing it shortly. Actually using the field, however, will require the setting to be configurable through the Segment dashboard. 

We will reach out to them in our capacity as partners, but would you also be able to reach out to your Segment rep requesting the enhancement to be made available in the Segment dashboard as well?

**Comment by Bucimis** [comment]
Available now, see https://segment.com/docs/destinations/braze/#in-app-messaging
