### ISSUE TITLE
Updating app boy to compile 'com.appboy:android-sdk-ui:2.2.5'

### ISSUE THREAD

**Issue by pranayairan** [Appboy/appboy-segment-android#8]
Hi,

Currently, this sdk is using old app boy compile 'com.appboy:android-sdk-ui:2.2.5' but there is a much newer version is available with breaking change on GcmReceiever to Fcm. 

Can we get an updated version so we can push the fix?

**Comment by ljzhanglc** [comment]
Hi Julian, 

Glad to know you're updating it.
The auto registration of tokens (FCM tokens) also doesn't seem to work with the appboy-segment sdk. I'm guessing it's because of the old appboy sdk as well (considering we have to use GCM)?  

Thanks.

**Comment by Bucimis** [comment]
@ljzhanglc that's correct - auto-fcm registration will be added in our next release through updating the Braze Android SDK version.

@pranayairan not a hard commitment but we expect to release within 1-2 weeks.  Our current plan is to add a new configuration parameter to the Segment/Braze dashboard - we're reaching out to segment now but there may be some lag there as well.

**Comment by Bucimis** [comment]
@pranayairan @ljzhanglc thanks all for your input - we just released a version of the Braze Segment SDK pointing to Braze Android SDK 3.0.1 with fcm auto-reg support.
