### ISSUE TITLE
Consider support for firebase token registration

### ISSUE THREAD

**Issue by ouchadam** [Appboy/appboy-segment-android#9]
Hello, 

It would be great if the integration could be configured with support for automatic firebase token registration, has this been considered?

**Comment by Bucimis** [comment]
Hi @ouchadam, this should already be supported, for more information see https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#added-9. If you don't have one already, you'll need to create an `appboy.xml` file in your `res/values`.

**Comment by ouchadam** [comment]
exactly what I was looking for, thanks!
